import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Instagram Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html >
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
